// Demo fallback data when Mistral API is unavailable
export const MOCK_SPERM_ANALYSIS = {
  documentType: 'Semen Analysis',
  detectedAs: 'Spermogram',
  date: 'March 2025',
  analyzedBy: 'Mistral OCR 3 + Small 4',
  biomarkers: [
    {
      name: 'Concentration',
      value: '42',
      unit: 'M/mL',
      norm: 'WHO norm ≥ 16 M/mL',
      normValue: 16,
      maxDisplayValue: 60,
      status: 'ok',
      interpretation: 'Your sperm concentration is excellent — well above the WHO minimum of 16 M/mL. This is one of the most important parameters and yours is strong.',
      tips: [
        { icon: '✅', text: 'Nothing specific to do — keep your current habits.' },
        { icon: '💧', text: 'Stay well hydrated (1.5–2L/day).' },
        { icon: '🌡️', text: 'Avoid sustained heat exposure (hot baths, sauna, laptop on lap).' },
      ],
    },
    {
      name: 'Volume',
      value: '3.2',
      unit: 'mL',
      norm: 'WHO norm ≥ 1.4 mL',
      normValue: 1.4,
      maxDisplayValue: 6,
      status: 'ok',
      interpretation: 'Your ejaculate volume is normal and above the WHO reference. This ensures sperm have enough fluid to travel effectively.',
      tips: [
        { icon: '✅', text: 'Volume is healthy — no specific action needed.' },
        { icon: '⏳', text: 'Abstinence of 2–7 days before a test gives the most reliable volume.' },
      ],
    },
    {
      name: 'Progressive motility',
      value: '28',
      unit: '%',
      norm: 'WHO norm ≥ 32%',
      normValue: 32,
      maxDisplayValue: 60,
      status: 'warn',
      interpretation: 'Your motility is slightly below the WHO threshold of 32%. This means a smaller proportion of sperm are moving forward efficiently. It can vary between samples and may not be significant in isolation.',
      tips: [
        { icon: '🥦', text: 'Increase antioxidants: zinc (pumpkin seeds), selenium (Brazil nuts), vitamin C & E.' },
        { icon: '🚭', text: 'Avoid tobacco — smoking is directly linked to reduced motility.' },
        { icon: '🏃', text: 'Moderate exercise 3–4x/week. Avoid overtraining which raises cortisol.' },
        { icon: '😴', text: 'Prioritize 7–8h of sleep. Poor sleep is correlated with lower sperm quality.' },
      ],
    },
    {
      name: 'Normal morphology',
      value: '3',
      unit: '%',
      norm: 'WHO norm ≥ 4% (Kruger)',
      normValue: 4,
      maxDisplayValue: 15,
      status: 'warn',
      interpretation: 'Morphology at 3% is mildly below the WHO reference of 4% (Kruger strict criteria). It\'s worth discussing with your doctor, especially combined with the motility result — but it\'s rarely the sole factor in fertility.',
      tips: [
        { icon: '🍇', text: 'Increase folate intake (leafy greens, legumes) — linked to better morphology.' },
        { icon: '🌡️', text: 'Strictly avoid heat exposure: hot baths, saunas, tight underwear.' },
        { icon: '🍷', text: 'Limit alcohol to maximum 1–2 drinks/week during this period.' },
        { icon: '🔄', text: 'A repeat test in 3 months (one spermatogenesis cycle) is recommended.' },
      ],
    },
  ],
  globalScore: 72,
  copilotSummary:
    'Your concentration is excellent. Motility (28%) and morphology (3%) are slightly below WHO norms — this is not necessarily alarming in isolation and can vary between samples. These results are very common and often improvable with lifestyle changes.',
  recommendations: [
    {
      icon: '🥦',
      text: 'Antioxidant-rich diet (zinc, selenium, vitamin E) supports sperm quality.',
      impact: 'Can improve motility by 5–15% and morphology by up to 10%.',
      timeline: 'Visible effect after 2–3 months (one sperm cycle).',
      habitLabel: 'Eat antioxidant-rich foods daily',
    },
    {
      icon: '🚭',
      text: 'Avoid tobacco and heat exposure (laptop on lap, hot baths).',
      impact: 'Smoking reduces motility by up to 20%. Heat directly damages sperm DNA.',
      timeline: 'Improvement starts within 3 months of stopping.',
      habitLabel: 'No heat exposure / no tobacco',
    },
    {
      icon: '🏃',
      text: 'Moderate exercise 3–4x/week is associated with better motility.',
      impact: 'Associated with +8–12% motility and better hormonal profile.',
      timeline: 'Measurable improvement after 6–8 weeks.',
      habitLabel: 'Exercise 3–4x per week',
    },
    {
      icon: '😴',
      text: 'Prioritize 7–8h of sleep — poor sleep is correlated with lower testosterone.',
      impact: 'Low testosterone reduces sperm production. Sleep restoration helps significantly.',
      timeline: 'Hormonal balance improves within 4–6 weeks of consistent sleep.',
      habitLabel: 'Sleep 7–8h per night',
    },
  ],
  questions: [
    { text: 'Given my progressive motility of 28%, do you recommend a repeat analysis or a DNA fragmentation test first?', badge: 'Based on your result', checked: true },
    { text: 'Is my morphology at 3% (Kruger) significant enough to consider ICSI over IUI?', badge: 'Based on your result', checked: true },
    { text: 'What protocol would you recommend as a first line — IUI or IVF — given our combined profile?', badge: 'Recommended', checked: false },
    { text: 'What lifestyle changes have the most evidence for improving motility specifically?', checked: false },
    { text: 'What are realistic timelines to start a first cycle?', checked: false },
  ],
}

export const MOCK_LAB_ANALYSIS = {
  documentType: 'Hormonal Panel',
  detectedAs: 'Hormonal Panel',
  date: 'February 2025',
  analyzedBy: 'Mistral OCR 3 + Small 4',
  biomarkers: [
    {
      name: 'AMH',
      value: '1.8',
      unit: 'ng/mL',
      norm: 'Normal: 1.0 – 3.5 ng/mL',
      normValue: 1.0,
      maxDisplayValue: 5,
      status: 'ok',
      interpretation: 'Your AMH reflects a good ovarian reserve for your age. AMH is the most reliable marker of egg supply.',
      tips: [
        { icon: '✅', text: 'Ovarian reserve looks healthy — maintain it with good lifestyle habits.' },
        { icon: '💊', text: 'Vitamin D and CoQ10 are associated with better ovarian response.' },
        { icon: '🚭', text: 'Smoking accelerates ovarian aging — avoid it completely.' },
      ],
    },
    {
      name: 'FSH (Day 3)',
      value: '8.2',
      unit: 'IU/L',
      norm: 'Normal: 3 – 10 IU/L',
      normValue: 10,
      maxDisplayValue: 15,
      status: 'ok',
      interpretation: 'Normal FSH level. A high FSH would indicate the body is working harder to stimulate the ovaries.',
      tips: [
        { icon: '✅', text: 'FSH is within range — no specific action needed.' },
        { icon: '😴', text: 'Sleep and stress management help maintain hormonal balance.' },
      ],
    },
    {
      name: 'LH (Day 3)',
      value: '5.4',
      unit: 'IU/L',
      norm: 'Normal: 2 – 15 IU/L',
      normValue: 15,
      maxDisplayValue: 20,
      status: 'ok',
      interpretation: 'Normal LH level. An LH/FSH ratio above 2 can suggest PCOS, but yours is balanced.',
      tips: [
        { icon: '✅', text: 'LH is balanced — no specific action needed.' },
      ],
    },
    {
      name: 'Estradiol (Day 3)',
      value: '42',
      unit: 'pg/mL',
      norm: 'Normal: 20 – 80 pg/mL',
      normValue: 80,
      maxDisplayValue: 100,
      status: 'ok',
      interpretation: 'Normal baseline estradiol. This hormone supports the uterine lining and is essential for ovulation.',
      tips: [
        { icon: '✅', text: 'Estradiol is within normal range.' },
        { icon: '🥗', text: 'Mediterranean diet supports healthy estrogen metabolism.' },
      ],
    },
  ],
  globalScore: 82,
  copilotSummary:
    'Your hormonal panel looks reassuring overall. AMH at 1.8 ng/mL reflects a good ovarian reserve for your age. All baseline hormones are within normal ranges — a solid foundation if treatment is needed.',
  recommendations: [
    {
      icon: '💊',
      text: 'Continue folic acid supplementation (400–800 mcg/day).',
      impact: 'Reduces neural tube defect risk and supports egg quality.',
      timeline: 'Best started 3 months before conception or treatment.',
      habitLabel: 'Take folic acid daily',
    },
    {
      icon: '😴',
      text: 'Prioritize 7–8h of sleep — it directly impacts ovarian response.',
      impact: 'Poor sleep disrupts LH/FSH balance and can reduce follicle response.',
      timeline: 'Hormonal improvement within 4–6 weeks of consistent sleep.',
      habitLabel: 'Sleep 7–8h per night',
    },
    {
      icon: '🥗',
      text: 'Mediterranean diet is associated with better IVF outcomes.',
      impact: 'Studies show up to 40% better IVF success rates vs. Western diet.',
      timeline: 'Benefits accumulate over 3+ months of consistent eating.',
      habitLabel: 'Follow Mediterranean diet',
    },
    {
      icon: '🧘',
      text: 'Stress management: yoga, meditation or therapy during treatment.',
      impact: 'Chronic stress elevates cortisol which suppresses reproductive hormones.',
      timeline: 'Measurable cortisol reduction within 3–4 weeks.',
      habitLabel: 'Daily stress management practice',
    },
  ],
  questions: [
    { text: 'My AMH is 1.8 ng/mL — is this level compatible with starting stimulation now, or would you recommend waiting?', badge: 'Based on your result', checked: true },
    { text: 'Given my hormonal baseline, which stimulation protocol would you recommend for me?', badge: 'Based on your result', checked: true },
    { text: 'What are the realistic success rates for IVF given my age and hormonal profile?', checked: false },
    { text: 'Are there any additional tests you would suggest before starting a protocol?', checked: false },
    { text: 'What lifestyle factors should I focus on most in the 3 months before stimulation?', checked: false },
  ],
}
